#! /bin/bash 
# Usage: $iron keystore <create|sho> <service> <client>
# Summary: create and show contents of java  keystore
# Help: This command groups commands used to create java keystore from pkcs#12 

APPNAME="iron"
CURRDIR=$(pwd)

RCDIR=$HOME/.$APPNAME
test -d $RCDIR || mkdir -p $RCDIR
CURRENT_TSTAMP=$(date '+%Y%m%d%H%M')

function certificate_create()
{
	service=$1
	client=$2
	CLIENT_CERTPATH=$RCDIR/$service/certs
	CP=$CLIENT_CERTPATH/$client
	test -d ${CP} || mkdir -p ${CP}
	openssl x509 -req -days 365 -CA $CAPATH/ca.crt -CAkey $CAPATH/ca.key -CAcreateserial -in $CP/$client.csr -out $CP/$client.crt
	test -f $CP/$client.crt && echo "Created certificate in [$CP/$client.crt]"
}

function keystore_show()
{
	service=$1
	client=$2
	CLIENT_CERTPATH=$RCDIR/$service/certs
	CP=$CLIENT_CERTPATH/$client
	test -d ${CP} || mkdir -p ${CP}
	echo "Showing content of KeyStore: [$CP/client.keystore]"
	keytool -keystore $CP/client.keystore -list -v
}

function keystore_create()
{
	service=$1
	client=$2
	CLIENT_CERTPATH=$RCDIR/$service/certs
	CP=$CLIENT_CERTPATH/$client
	test -d ${CP} || mkdir -p ${CP}
	echo "Insert PKCS#12 (*.p12) keystore password:"
	read keystore_password
	keytool -importkeystore \
        -deststorepass "${keystore_password}" -destkeypass "${keystore_password}" -destkeystore $CP/client.keystore \
        -srckeystore $CP/${client}.p12 -srcstoretype PKCS12 -srcstorepass "${keystore_password}" \
        -alias "${client}"

	test -f $CP/client.keystore && echo "Created Java Keystore in [$CP/client.keystore]"
}

if [ "$#" = 3 ];then
	operation=$1
	service=$2
	CA_RCFILE="$HOME/"."$APPNAME/default-ca"".env"
	source ${CA_RCFILE}

	if [ "$operation" = "create" ]; then
		client=$3
		keystore_create $service $client
	fi 

	if [ "$operation" = "show" ]; then
		client=$3
		keystore_show $service $client
	fi 

else
	echo "Usage:"
	echo "\$iron keystore create <service> <client-id>"
	echo "\$iron keystore show <service> <client-id>"
	exit -1
fi
